import type { Metadata } from "next";

import "./globals.css";

import Contact from "@/components/landing/footer/contact";
import Navbar from "@/components/landing/header/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Contact />
      </body>
    </html>
  );
}
